title: Julian Laubstein’s blog
email: contact@julianlaubstein.de
description: > # this means to ignore newlines until "baseurl:"
  Blog of Julian Laubstein. Trust me, it's not as cool as it sounds.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com=
github_username:  sphinxc0re

# Build settings
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
